### ISSUE TITLE
Load README via fetch

### ISSUE THREAD

**Issue by shgysk8zer0** [KVSun/ad-insertion#47]
While having this load with the page is _mostly_ a good thing, the lack of caching of Gitter badge causes a significant increase load times.

Load it using `fetch`, probably on a click event.

**Comment by shgysk8zer0** [comment]
First need to implement MutationObserver

**Comment by shgysk8zer0** [comment]
Created #48 for implementing `MutationObserver`

**Comment by kvsun-editor** [comment]
Completed in pull-request #54
